{
    "name": "eSMIS - Philippines",
    "version": "19.0.1.0.0",
    "category": "eSMIS",
    "summary": "Student Management Information System for Philippine HEIs",
    "author": "Pith Technologies",
    "website": "",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": [],
    "depends": [
        "esmis_base",
        "esmis_vocabulary",
        "esmis_security",
        "esmis_consent",
        "esmis_approval",
        "esmis_student",
        "esmis_address",
        "esmis_ph",
    ],
    "data": [
        "data/res_company_data.xml",
    ],
    "auto_install": False,
    "application": True,
    "installable": True,
}
