{
    "name": "eSMIS - Philippines",
    "version": "19.0.1.0.0",
    "category": "eSMIS/Localization",
    "summary": "Philippine-specific extensions for eSMIS",
    "depends": ["esmis_student", "esmis_address"],
    "data": [
        "security/ir.model.access.csv",
        "data/vocabulary_name_suffix.xml",
        "data/vocabulary_ethnicity_ph.xml",
        "data/vocabulary_religion_ph.xml",
        "data/vocabulary_identifier_type_ph.xml",
        "data/psgc_regions.xml",
        "data/psgc_provinces.xml",
        "data/psgc_cities_municipalities.xml",
        "views/res_partner_views.xml",
        "views/address_views.xml",
        "views/psgc_views.xml",
    ],
    "excludes": [],
    "post_init_hook": "post_init_hook",
    "auto_install": False,
    "application": False,
    "installable": True,
    "license": "LGPL-3",
}
