{
    "name": "Vocabulary",
    "version": "19.0.1.0.0",
    "category": "eSMIS/Core",
    "summary": "Configurable code lists for operational and administrative data",
    "author": "Your Organization",
    "website": "",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": [],
    "depends": ["base"],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "views/vocabulary_views.xml",
        "views/vocabulary_code_views.xml",
        "views/menus.xml",
        "data/vocabulary_gender.xml",
        "data/vocabulary_civil_status.xml",
        "data/vocabulary_blood_type.xml",
        "data/vocabulary_academic_period_type.xml",
        "data/vocabulary_year_level.xml",
        "data/vocabulary_student_status.xml",
        "data/vocabulary_enrollment_status.xml",
        "data/vocabulary_grade_remark.xml",
        "data/vocabulary_degree_type.xml",
        "data/vocabulary_document_type.xml",
        "data/vocabulary_relationship_type.xml",
        "data/vocabulary_disability_type.xml",
        "data/vocabulary_scholarship_type.xml",
    ],
    "auto_install": False,
    "application": False,
    "installable": True,
}
