{
    "name": "eSMIS Student",
    "version": "19.0.1.0.0",
    "category": "eSMIS/Core",
    "summary": "Universal student demographics on res.partner with education history",
    "author": "Pith Technologies",
    "website": "",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": [],
    "depends": ["esmis_base", "mail", "esmis_vocabulary", "esmis_security", "esmis_consent", "esmis_address"],
    "external_dependencies": {"python": ["cryptography"]},
    "data": [
        "security/categories.xml",
        "security/privileges.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/vocabulary_education_level.xml",
        "views/res_partner_student_views.xml",
        "views/identifier_views.xml",
        "views/education_history_views.xml",
        "views/menus.xml",
    ],
    "demo": [
        "demo/demo_students.xml",
        "demo/demo_identifiers.xml",
    ],
    "auto_install": False,
    "application": False,
    "installable": True,
}
